# export ANSIBLE_CONFIG=./ansible.cfg && ansible-playbook -i ./hosts/hosts ./example_with_httpapi/fortios_user_device_example.yml
- hosts: fortigates
  connection: httpapi
  gather_facts: False

  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  
  tasks:
  - name: Configure devices.
    fortios_user_device:
      vdom:  "{{ vdom }}"
      state: "present"
      user_device:
        category: "none"
        alias: "myuser"
        comment: "Comment."
        mac: "00:01:04:03:ab:c3:32"
        type: "android-phone"
        user: "my_user"